name: Chrome Docker

on: 
  repository_dispatch:
  types: [custom_event_type]
  schedule:
    - cron: '5 12 * * 0'

jobs:
  # run Chrome inside a Docker container
  chrome:
    runs-on: ubuntu-latest
    # https://github.com/cypress-io/cypress-docker-images
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Chrome
        uses: cypress-io/github-action@v4
        timeout-minutes: 10
        with:
          build: npm run build
          start: npm start
          browser: chrome
